export default {
    MAIN: "/",
    VACANCY: "/vacancy/:id",
    VACANCYLINK: "/vacancy/",
    ABOUTUS: "/aboutUs",
    CONTACTS: "/contacts",
    COOPERATION: "/cooperation/:id",
    COOPERATIONLINK: "/cooperation/",
    NEWS: "/news/:id",
    NEWSLINK: "/news/",
    CURRENTNEWS: "/current-news/:id",
    CURRENTNEWSLINK: "/current-news/",
    DIRECTIONS: "/directions/:id",
    DIRECTIONSLINK: "/directions/",
};
